### ISSUE TITLE
Change crate name to vyper-cli

### ISSUE THREAD

**Issue by giacomo-cc** [vyper-protocol/vyper-cli#33]
https://github.com/vyper-protocol/vyper-cli/blob/4fd49327c8c362b6091fd68f763e14623525422c/Cargo.toml#L2

after this change we'll need to change also the website
from
https://vyper-protocol.github.io/vyper-cli/vyper/
to
https://vyper-protocol.github.io/vyper-cli/vyper-cli/

**Comment by iamakshat01** [comment]
If i change the name to vyper-cli user will need to write commands as `vyper-cli core fetch`. Not sure if there is a way.
